// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDemanderInfo = "demander_info"

// DemanderInfo mapped from table <demander_info>
type DemanderInfo struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                        // 主键
	Name       string    `gorm:"column:name;not null" json:"name"`                                         // 广告主名称
	Username   string    `gorm:"column:username;not null" json:"username"`                                 // 账户
	Password   string    `gorm:"column:password;not null" json:"password"`                                 // 密码
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	ModifyTime time.Time `gorm:"column:modify_time;not null;default:CURRENT_TIMESTAMP" json:"modify_time"` // 修改时间
}

// TableName DemanderInfo's table name
func (*DemanderInfo) TableName() string {
	return TableNameDemanderInfo
}
